wandb_version: 1

stack_net:
  desc: null
  value:
    geometry_embeddings:
    - geometry_embed:
        degrees:
        - 1
        - 2
        radial_basis_function: phys
        n_rbf: 32
        radial_cutoff_fn: cosine_cutoff_fn
        r_cut: 5
        sphc: true
        sphc_normalization: null
        solid_harmonic: false
        mic: false
        input_convention: positions
        prop_keys:
          energy: E
          force: F
          atomic_position: R
          atomic_type: z
          idx_i: idx_i
          idx_j: idx_j
          unit_cell: unit_cell
          pbc: pbc
          cell_offset: cell_offset
          stress: stress
          node_mask: node_mask
    - one_hot_embed:
        atomic_types:
        - 1
        - 6
        - 8
        prop_keys:
          energy: E
          force: F
          atomic_position: R
          atomic_type: z
          idx_i: idx_i
          idx_j: idx_j
          unit_cell: unit_cell
          pbc: pbc
          cell_offset: cell_offset
          stress: stress
          node_mask: node_mask
    feature_embeddings:
    - atom_type_embed:
        num_embeddings: 100
        features: 32
        prop_keys:
          energy: E
          force: F
          atomic_position: R
          atomic_type: z
          idx_i: idx_i
          idx_j: idx_j
          unit_cell: unit_cell
          pbc: pbc
          cell_offset: cell_offset
          stress: stress
          node_mask: node_mask
    layers:
    - so3kratace_layer:
        fb_filter: radial_spherical
        fb_rad_filter_features:
        - 32
        - 32
        fb_sph_filter_features:
        - 8
        - 32
        fb_attention: conv_att
        gb_filter: radial_spherical
        gb_rad_filter_features:
        - 32
        - 32
        gb_sph_filter_features:
        - 8
        - 32
        gb_attention: conv_att
        n_heads: 2
        degrees:
        - 1
        - 2
        max_body_order: 3
        bo_features: 16
        n_node_type: 3
        layer_normalization: false
        sphc_normalization: false
        final_layer: false
    - so3kratace_layer:
        fb_filter: radial_spherical
        fb_rad_filter_features:
        - 32
        - 32
        fb_sph_filter_features:
        - 8
        - 32
        fb_attention: conv_att
        gb_filter: radial_spherical
        gb_rad_filter_features:
        - 32
        - 32
        gb_sph_filter_features:
        - 8
        - 32
        gb_attention: conv_att
        n_heads: 2
        degrees:
        - 1
        - 2
        max_body_order: 3
        bo_features: 16
        n_node_type: 3
        layer_normalization: false
        sphc_normalization: false
        final_layer: false
    observables:
    - energy:
        per_atom_scale: null
        per_atom_shift: null
        num_embeddings: 100
        output_convention: per_structure
        prop_keys:
          energy: E
          force: F
          atomic_position: R
          atomic_type: z
          idx_i: idx_i
          idx_j: idx_j
          unit_cell: unit_cell
          pbc: pbc
          cell_offset: cell_offset
          stress: stress
          node_mask: node_mask
    prop_keys:
      energy: E
      force: F
      atomic_position: R
      atomic_type: z
      idx_i: idx_i
      idx_j: idx_j
      unit_cell: unit_cell
      pbc: pbc
      cell_offset: cell_offset
      stress: stress
      node_mask: node_mask
    n_layers: 2
optimizer:
  desc: null
  value:
    learning_rate: 0.001
    transition_steps: null
    decay_rate: null
    weight_decay: null
    clip_by_global_norm: null
coach:
  desc: null
  value:
    inputs:
    - atomic_position
    - atomic_type
    - idx_i
    - idx_j
    - node_mask
    targets:
    - energy
    - force
    epochs: 1000
    training_batch_size: 5
    validation_batch_size: 5
    loss_weights:
      energy: 0.01
      force: 0.99
    ckpt_dir: ckpt_dir/module_2
    data_path: example_data/ethanol.npz
    training_seed: 0
    net_seed: 0
    stop_lr_min: null
    stop_metrics_min: null
dataset:
  desc: null
  value:
    split:
      n_train: 200
      n_valid: 200
      n_test: 1600
      n_data: 2000
      r_cut: 5
      mic: false
train_state:
  desc: null
  value:
    plateau_lr_decay:
      patience: 50
      decay_factor: 1.0
    scheduled_lr_decay:
      exponential:
        transition_steps: 10000
        decay_factor: 0.9
    lr_warmup: null
_wandb:
  desc: null
  value:
    python_version: 3.8.9
    cli_version: 0.15.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687413472.510428
    t:
      1:
      - 5
      - 12
      - 45
      - 53
      - 55
      2:
      - 5
      - 12
      - 45
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.9
      5: 0.15.2
      8:
      - 5
